services:
  db:
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: books_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    volumes:
      - db-data:/var/lib/mysql

  node-service:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    environment:
      DB_HOST: db
      DB_USERNAME: db_user
      DB_PASSWORD: db_password
      DB_DATABASE: books_db
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    depends_on:
      - node-service
    ports:
      - "8080:80"

volumes:
  db-data:
